language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
install:
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - sudo apt-get update
  - sudo apt-get build-dep python-pygame
  - sudo apt-get install python-dev libv4l-dev
  - sudo apt-get install python-pygame

before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 src"
  - pyflakes -x W src
script:
  - python -m py_compile src
